name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install pipenv
      run: sudo pip install pipenv
    - name: Setup pipenv
      run: pipenv sync --dev
    - name: Run test suite
      run: pipenv run pytest -vv
    - name: Check black formatting
      run: pipenv run black --check .
    - name: Mypy
      run: pipenv run mypy tornado_async_transformer
    - name: Deploy to pypi
      if: github.ref == 'refs/heads/master'
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: pipenv run bundle && pipenv run deploy
